trigger:
  branches:
    include:
    - master
  paths:
    include:
    - iac/arm-templates/*

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: devopsforai-aml-vg
- name: baseName
  value: $[coalesce(variables['baseNameOverride'], 'mlopsdb')]
- name: location
  value: $[coalesce(variables['locationOverride'], 'westus2')]
- name: azuresub
  value: $[coalesce(variables['azuresubOverride'], 'davete02_sub')]

steps:
- task: AzureResourceGroupDeployment@2
  inputs:
    azureSubscription: $(azuresub)
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(baseName)-AML-RG'
    location: $(location)
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/iac/arm-templates/cloud-environment.json'
    overrideParameters: '-baseName $(baseName) -adbPricingTier standard'
    deploymentMode: 'Incremental'
  displayName: 'Deploy MLOps resources to Azure'